---
title: "Berisp-like: a trophic model of contamination"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example of Trophic Contamination}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=10,
  fig.height=5,
  warning = FALSE,
  message = FALSE
)
```

```{r setup}
library(spacemodR)
```

```{r add_function, echo=FALSE}
# ADDITIONAL FUNCTION
read_sf_safe <- function(file_path) {
  paths <- c("", "../", "../../") |> paste0(file_path)
  valid_path <- paths[file.exists(paths)][1]
  if (!is.na(valid_path)) {
    return(sf::read_sf(valid_path))
  }
  warning("File not found at: ", paste(paths, collapse = " OR "))
  return(NULL)
}
load_safe <- function(file_path) {
  paths <- c("", "../", "../../") |> paste0(file_path)
  valid_path <- paths[file.exists(paths)][1]
  if (!is.na(valid_path)) {
    return(readRDS(valid_path))
  }
  warning("File not found at: ", paste(paths, collapse = " OR "))
  return(NULL)
}
```

# Define a Spacemodel

## Habitat

```{r}
ground_cd <- load_raster_extdata("ground_concentration_cd_compressed.tif")
names_hab = c("soil", "plant", "earthwom", "carabid", "mamHerb", "mamInsect")
list_habitat <- lapply(names_hab, function(i) ground_cd)
stack_habitat <- raster_stack(list_habitat, names_hab)

terra::plot(stack_habitat)
```

## Trophic web

```{r}
trophic_df <- trophic() |>
  add_link("soil", "plant", 1) |>
  add_link("soil", "earthwom", 1) |>
  add_link("soil", "carabid", 1) |>
  # mamHerb
  add_link("soil", "mamHerb", 2/100) |>
  add_link("plant", "mamHerb", 90/100) |>
  add_link("earthwom", "mamHerb", 4/100) |>
  add_link("carabid", "mamHerb", 4/100) |>
  # mamInsect
  add_link("soil", "mamInsect", 2/100) |>
  add_link("earthwom", "mamInsect", 49/100) |>
  add_link("carabid", "mamInsect", 49/100)
```

```{r}
plot(trophic_df)
```

# Contaminantion by Cadmium


```{r load_data, echo=FALSE}
fit_simple_veg_cd <- load_safe("raw_data/fit_simple_veg_cd.rds")
fit_simple_worm_cd <- load_safe("raw_data/fit_simple_worm_cd.rds")
```

## Vegetation

```{r, echo=FALSE}
fit_pars <- rstan::extract(fit_simple_veg_cd, c("beta0", "beta1"))
df_pars <- dplyr::bind_rows(list(
  data.frame(value=fit_pars$beta0, par="beta0"),
  data.frame(value=fit_pars$beta1, par="beta1")
))
inter_veg = median(df_pars$beta0, na.rm=TRUE)
slope_veg = median(df_pars$beta1, na.rm=TRUE)
```


## Earthworm

For Cadmium, the equation is given by (Ma et al., 2004):

$$
\log C_{earthworm} = a + b \times \log C_{soil} + c \times \log OM + d \times pH
$$

```{r, echo=FALSE}
fit_pars <- rstan::extract(fit_simple_veg_cd, c("beta0", "beta1"))
df_pars <- dplyr::bind_rows(list(
  data.frame(value=fit_pars$beta0, par="beta0"),
  data.frame(value=fit_pars$beta1, par="beta1")
))
inter_worm = median(df_pars$beta0, na.rm=TRUE)
slope_worm = median(df_pars$beta1, na.rm=TRUE)
```

## Carabid

```{r}
inter_carab = -1
slope_carab = 0.6
```


## Transfer of food

$$
C = \frac{1}{b} \times \frac{food \times C_{food} \times c_{up}}{C_{out}} \left( 1 - \exp^{- c_{out} \times a} \right)
$$
where:

- $b$: average individual biomass $[g]$,
- $c_{up}$: assimilation efficiency of food  $[n.d.]$,
- $c_{out}$: excretion rate of food, $[day^{-1}]$
- $a$: average age $[day]$,
- $

